name: download_env
channels: 
        - conda-forge
dependencies:
        - python=3.7
        - click
        - pathlib
        - xarray=0.14.1
        - dask
        - netCDF4
        - motuclient
        - cdsapi
