name: download_env
channels: 
        - conda-forge
dependencies:
        - python=3.7
        - click
        - pathlib
        - xarray
        - dask
        - netCDF4
        - motuclient
        - cdsapi